export const USER_FETCH_FULFILLED = 'USER_FETCH_FULFILLED';
export const USER_FETCH_REJECTED = 'USER_FETCH_REJECTED';
export const INPUT_SEARCH = 'INPUT_SEARCH';
export const USER_FILTER = 'USER_FILTER';
export const USER_FETCH = 'USER_FETCH';
export const USER_SORT = 'USER_SORT';
